// Auth.js v5 catch-all route — exposes the GET/POST handlers generated by
// NextAuth() at /api/auth/*.
//
// Endpoints handled by Auth.js (subset):
//   POST /api/auth/callback/credentials  — credentials sign-in
//   POST /api/auth/signout               — sign-out
//   GET  /api/auth/session               — current session (read-only)
//   GET  /api/auth/csrf                  — CSRF token

import { handlers } from '@/auth';

export const { GET, POST } = handlers;
